<?php

// Used to test if the website is called from the webpack dev server
function isWebpack() {
  return !!(
    isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    && $_SERVER['HTTP_X_FORWARDED_FOR'] == 'webpack'
  );
}

// Used instead for all CSS files generated by webpack.
// This will enable the livereload feature when in development
function liveCSS ($href, $media = null) {
  return isWebpack()
    ? '<script src="'. $href .'"></script>'
    : '<link rel="stylesheet" href="'. $href .'" '. ($media ? 'media="'. $media .'"' : '') .'>';
}
